"""initialization

Revision ID: 3d4234e7f162
Revises: 
Create Date: 2022-05-13 23:34:09.927624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4234e7f162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('elective',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=True),
                    sa.Column('short_description', sa.String(length=50), nullable=True),
                    sa.Column('full_description', sa.String(length=255), nullable=True),
                    sa.Column('minor', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(tuple(['minor']), ['minor.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('test')
    op.drop_table('author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
                    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
                    )
    op.create_table('test',
                    sa.Column('new_column', sa.VARCHAR(), autoincrement=False, nullable=True)
                    )
    op.drop_table('elective')
    op.drop_table('minor')
    # ### end Alembic commands ###
